version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=blog_app
      - DB_USERNAME=blog_user
      - DB_PASSWORD=blog_password
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: mysql:8.0
    container_name: blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: blog_app
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - blog-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: blog_user
      PMA_PASSWORD: blog_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - blog-network

volumes:
  db_data:

networks:
  blog-network:
    driver: bridge
